.\"     Title: MSCORE
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 14 Aug 2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "MSCORE" "1" "14 Aug 2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
mscore \- Graphical musical score editor
.SH "SYNOPSIS"
.HP 7
\fBmscore\fR [\fB\ \-v\ \fR] [\fB\ \-d\ \fR] [\fB\ \-s\ \fR] [\fB\ \-m\ \fR] [\fB\ \-L\ \fR] [\fB\ \-i\ \fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBmscore\fR
and
\fBbar\fR
commands.
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page. Instead, it has documentation in the
GNU
Info
format; see below.
.PP
\fBmscore\fR
is a program for editing musical scores.
.SH "OPTIONS"
.PP
This program takes options starting with a single dash (`\-'). A summary of options is included below.
.PP
\fB\-v\fR
.RS 4
print version.
.RE
.PP
\fB\-d\fR
.RS 4
debug mode.
.RE
.PP
\fB\-s\fR
.RS 4
no internal synthesizer.
.RE
.PP
\fB\-m\fR
.RS 4
no midi.
.RE
.PP
\fB\-L\fR
.RS 4
layout debug.
.RE
.PP
\fB\-i\fR
.RS 4
dump midi input.
.RE
.SH "SEE ALSO"
.PP
muse (1).
.SH "AUTHOR"
.PP
This manual page was written by Junichi Uekawa
<dancer@debian.org>
for the
Debian(TM)
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL.
.SH "COPYRIGHT"
Copyright \(co 2007 Junichi Uekawa
.br

