#!/bin/sh

echo "TRANSLATIONS = \\"
echo "      $1/share/locale/mscore_da.ts \\"
echo "      $1/share/locale/mscore_de.ts \\"
echo "      $1/share/locale/mscore_ru.ts \\"
echo "      $1/share/locale/mscore_it.ts \\"
echo "      $1/share/locale/mscore_es.ts \\"
echo "      $1/share/locale/mscore_fi.ts \\"
echo "      $1/share/locale/mscore_fr.ts \\"
echo "      $1/share/locale/mscore_nl.ts \\"
echo "      $1/share/locale/mscore_cz.ts \\"
echo "      $1/share/locale/mscore_gl.ts \\"
echo "      $1/share/locale/mscore_tr.ts \\"
echo "      $1/share/locale/mscore_hi_IN.ts \\"
echo "      $1/share/locale/mscore_pt_BR.ts \\"
echo "      $1/share/locale/mscore_pt.ts \\"
echo "      $1/share/locale/mscore_sv.ts \\"
echo "      $1/share/locale/mscore_no.ts \\"
echo "      $1/share/locale/mscore_en_GB.ts"

echo "FORMS = \\"
uis=`find $1/mscore -name "*.ui"`
for a in $uis; do
      echo "    " $a \\;
      done
echo

echo "SOURCES = \\"
uis=`find $1/mscore -name "*.cpp"`
for a in $uis; do
      echo "    " $a \\;
      done
echo
echo
