#!/bin/bash

#
#     this script tries to produce a fake debian package
#

VERSION="0.4"

echo "creating fake *.deb package"
mkdir debian
cd debian

#
#     copy data
#

mkdir usr
mkdir usr/bin
mkdir usr/share
mkdir usr/share/mscore-${VERSION}
mkdir usr/share/mscore-${VERSION}/doc
mkdir usr/share/mscore-${VERSION}/templates
mkdir usr/share/mscore-${VERSION}/wallpapers
cp ../build/mscore/mscore usr/bin
cp ../mscore/share/templates/*.xml   usr/share/mscore-${VERSION}/templates
cp ../mscore/share/templates/*.msc   usr/share/mscore-${VERSION}/templates
cp ../mscore/share/wallpaper/*.png  usr/share/mscore-${VERSION}/wallpapers
cp ../build/doc/de/man-de.pdf usr/share/mscore-${VERSION}/doc
cp ../build/doc/en/man-en.pdf usr/share/mscore-${VERSION}/doc

#
#     create DEBIAN
#

mkdir DEBIAN
cd DEBIAN
echo "Package: mscore" > control
echo "Version: ${VERSION}-0ubuntu0.1" >> control
echo "Section: multimedia" >> control
echo "Priority: optional" >> control
echo "Architecture: i386" >> control
echo "Essential: no" >> control
echo "Installed-Size: 10000000" >> control
echo "Maintainer: ws<ws@seh.de>" >> control
echo "Depends: libqt4-core (>= 4.2), libqt4-gui (>= 4.2)" >> control
echo "Description: music score editor" >> control
echo "   music score editor" >> control

# pre install script
# echo "#!/bin/sh" > preinst
# chmod 755 preinst

# post install script
# echo "#!/bin/sh" > postinst
# chmod 755 postinst

# remove temp files created by the package
#echo "#!/bin/sh" > postrm
#chmod 755 postrm
cd ..

#
#     create archiv
#

cd ..
dpkg-deb -b debian mscore_${VERSION}-0.1.deb

