#!/bin/bash

MSCORE=../../build/mscore/mscore

echo "------------------------------"
echo "Regression Tests for MuseScore"
echo "------------------------------"
echo
$MSCORE -v
echo

testcount=0
failures=0

rwtest() {
      echo -n "testing load/save $1";
      $MSCORE $1 -o mops.msc &> /dev/null
      if diff -q $1 mops.msc &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $1 mops.msc
            echo "+++++++++++++++++++++++++++"
      fi
      testcount=$(($testcount+1))
      }

rwtestXml() {
      echo -n "testing load/save $1";
      $MSCORE $1 -d -o mops.xml &> /dev/null
      if diff -q $1 mops.xml &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $1 mops.xml
            echo "+++++++++++++++++++++++++++"
      fi
      testcount=$(($testcount+1))
      }

rwtestAllDemos() {
      rwtest ../demos/promenade.msc
      rwtest ../demos/adeste.msc
      rwtest ../demos/inv10.msc
      rwtest ../demos/inv13.msc
      rwtest ../demos/inv1.msc
      rwtest ../demos/inv6.msc
      rwtest ../demos/praeludium1.msc
      rwtest ../demos/prelude.msc
      rwtest ../demos/scales.msc
      rwtest ../demos/sonata16.msc
      rwtest ../demos/bach-bc2.msc
      }

rwtestAllMsc() {
      rwtest accidental1.msc
      rwtest accidental2.msc
      rwtest chromatic.msc
      rwtest coda.msc
      rwtest crossbeams.msc
      rwtest RepeatTest6.msc
      rwtest RepeatTest7.msc
      rwtest scales1.msc
      rwtest slur2.msc
      rwtest test1.msc
      rwtest test2.msc
      rwtest test7.msc
      rwtest testKeysig2.msc
      rwtest testsmall.msc
      rwtest testTimesig2.msc
      rwtest tuplets.msc
      }

rwtestAllXml() {
      rwtestXml testAccidentals1.xml
      rwtestXml testAccidentals2.xml
      rwtestXml testBarStyles.xml
      rwtestXml testDCalCoda.xml
      rwtestXml testDCalFine.xml
      rwtestXml testDalSegno.xml
      rwtestXml testDirections1.xml
      rwtestXml testDynamics1.xml
      rwtestXml testDynamics2.xml
      rwtestXml testHello.xml
      rwtestXml testImplicitMeasure1.xml
      rwtestXml testKeysig1.xml
      rwtestXml testLines1.xml
      rwtestXml testNoteAttributes1.xml
      rwtestXml testNoteAttributes2.xml
      rwtestXml testNotesRests1.xml
      rwtestXml testSystemBrackets1.xml
      rwtestXml testSystemBrackets2.xml
      rwtestXml testTimesig1.xml
      rwtestXml testTimesig3.xml
      rwtestXml testTremolo.xml
      rwtestXml testVoicePiano1.xml
      rwtestXml testVolta1.xml
      rwtestXml testWedge1.xml
      rwtestXml testWords1.xml
      }

usage() {
      echo "usage: $0 [demos | msc | xml]"
      echo
      exit 1
      }

if [ $# -eq 0 ]; then
      rwtestAllDemos
      rwtestAllMsc
      rwtestAllXml
elif [ $# -eq 1 ]; then
      if [ "$1" == "demos" ]; then
            rwtestAllDemos
      elif [ "$1" == "msc" ]; then
            rwtestAllMsc
      elif [ "$1" == "xml" ]; then
            rwtestAllXml
      else
            usage
      fi
elif [ $# -ge 2 ]; then
      usage
fi

echo
echo "$testcount test(s), $failures failure(s)"
