#!/bin/bash

MSCORE=../../build/mscore/mscore

echo "------------------------------"
echo "Regression Tests for MuseScore"
echo "------------------------------"
echo
$MSCORE -v
echo

testcount=0
failures=0

rwtest() {
      echo -n "testing load/save $1";
      $MSCORE $1 -o mops.msc &> /dev/null
      if diff -q $1 mops.msc &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            exit 1;
      fi
      testcount=$(($testcount+1))
      }

rwtest ../demos/promenade.msc
rwtest ../demos/adeste.msc
rwtest ../demos/inv10.msc
rwtest ../demos/inv13.msc
rwtest ../demos/inv1.msc
rwtest ../demos/inv6.msc
rwtest ../demos/praeludium1.msc
rwtest ../demos/prelude.msc
rwtest ../demos/scales.msc
rwtest ../demos/sonata16.msc
rwtest ../demos/bach-bc2.msc

rwtest accidental1.msc
rwtest accidental2.msc
rwtest chromatic.msc
rwtest crossbeams.msc
rwtest RepeatTest6.msc
rwtest scales1.msc
rwtest slur2.msc
rwtest test1.msc
rwtest test2.msc
rwtest test7.msc
rwtest testKeysig2.msc
rwtest testTimesig2.msc
rwtest tuplets.msc

echo
echo "$testcount test(s), $failures failure(s)"

