#!/bin/bash

MSCORE=../../build/mscore/mscore

echo "------------------------------"
echo "Regression Tests for MuseScore"
echo "------------------------------"
echo
$MSCORE -v
echo

testcount=0
failures=0

rwtest() {
      echo -n "testing load/save $1";
      $MSCORE $1 -o mops.msc &> /dev/null
      if diff -q $1 mops.msc &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
      fi
      testcount=$(($testcount+1))
      }

rwtest ../demos/promenade.msc
rwtest ../demos/adeste.msc

echo
echo "$testcount test(s), $failures failure(s)"

