#!/bin/bash

MSCORE=../../build/mscore/mscore

echo "------------------------------"
echo "Regression Tests for MuseScore"
echo "------------------------------"
echo
$MSCORE -v
echo

testcount=0
failures=0

rwtest() {
      echo -n "testing load/save $1";
      $MSCORE $1 -o mops.mscx &> /dev/null
      if diff -q $1 mops.mscx &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $1 mops.mscx
            echo "+++++++++++++++++++++++++++"
      fi
      rm mops.mscx
      testcount=$(($testcount+1))
      }

rwtestBww() {
      echo -n "testing load/save $1";
      REF=bwwrefs/`basename $1 .bww`.xml
      $MSCORE ../bww2mxml/test/$1 -d -o mops.xml &> /dev/null
      if diff -q $REF mops.xml &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $REF mops.xml
            echo "+++++++++++++++++++++++++++"
      fi
      rm mops.xml
      testcount=$(($testcount+1))
      }

rwtestXml() {
      echo -n "testing load/save $1";
      $MSCORE $1 -d -o mops.xml &> /dev/null
      if diff -q $1 mops.xml &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $1 mops.xml
            echo "+++++++++++++++++++++++++++"
      fi
      rm mops.xml
      testcount=$(($testcount+1))
      }

rwtestXmlRef() {
      echo -n "testing load/save $1";
      REF=musicxml/`basename $1 .xml`_ref.xml
      $MSCORE $1 -d -o mops.xml &> /dev/null
      if diff -q $REF mops.xml &> /dev/null; then
            echo -e "\r\t\t\t\t\t\t...OK";
      else
            echo -e "\r\t\t\t\t\t\t...FAILED";
            failures=$(($failures+1));
            echo "+++++++++DIFF++++++++++++++"
            diff $REF mops.xml
            echo "+++++++++++++++++++++++++++"
      fi
      rm mops.xml
      testcount=$(($testcount+1))
      }

rwtestAllBww() {
      rwtestBww testBeams.bww
      rwtestBww testDuration.bww
      rwtestBww testGraces.bww
      rwtestBww testHello.bww
      rwtestBww testMidMeasureRepeat.bww
      rwtestBww testNotes.bww
      rwtestBww testNoTimeSig1.bww
      rwtestBww testNoTimeSig2.bww
      rwtestBww testRepeats.bww
      rwtestBww testTempo60.bww
      rwtestBww testTempo120.bww
      rwtestBww testTieTriplet.bww
      rwtestBww testTriplets.bww
      }

rwtestAllDemos() {
      rwtest ../demos/promenade.mscx
      rwtest ../demos/adeste.mscx
      rwtest ../demos/inv10.mscx
      rwtest ../demos/inv13.mscx
      rwtest ../demos/inv1.mscx
      rwtest ../demos/inv6.mscx
      rwtest ../demos/praeludium1.mscx
      rwtest ../demos/prelude.mscx
      rwtest ../demos/scales.mscx
      rwtest ../demos/sonata16.mscx
      rwtest ../demos/bach-bc2.mscx
      }

rwtestAllMsc() {
      rwtest msc/accidental1.msc
      rwtest msc/accidental2.msc
      rwtest msc/chromatic.msc
      rwtest msc/coda.msc
      rwtest msc/crossbeams.msc
      rwtest msc/RepeatTest6.msc
      rwtest msc/RepeatTest7.msc
      rwtest msc/scales1.msc
      rwtest msc/slur2.msc
      rwtest msc/test1.msc
      rwtest msc/test2.msc
      rwtest msc/test7.msc
      rwtest msc/testKeysig2.msc
      rwtest msc/testsmall.msc
      rwtest msc/testTimesig2.msc
      rwtest msc/tuplets.msc
      }

rwtestAllXml() {
      rwtestXml musicxml/testAccidentals1.xml
      rwtestXml musicxml/testAccidentals2.xml
      rwtestXml musicxml/testArpGliss1.xml
      rwtestXml musicxml/testArpGliss2.xml
      rwtestXml musicxml/testBarStyles.xml
      rwtestXml musicxml/testClefs1.xml
      rwtestXml musicxml/testDalSegno.xml
      rwtestXml musicxml/testDCalCoda.xml
      rwtestXml musicxml/testDCalFine.xml
      rwtestXml musicxml/testDirections1.xml
      rwtestXml musicxml/testDynamics1.xml
      rwtestXml musicxml/testDynamics2.xml
      rwtestXmlRef musicxml/testDynamics3.xml
      rwtestXml musicxml/testGrace1.xml
      rwtestXml musicxml/testGrace2.xml
      rwtestXml musicxml/testHarmony1.xml
      rwtestXml musicxml/testHarmony2.xml
      rwtestXml musicxml/testHello.xml
      rwtestXml musicxml/testImplicitMeasure1.xml
      rwtestXml musicxml/testInvisibleElements.xml
      rwtestXml musicxml/testKeysig1.xml
      rwtestXmlRef musicxml/testLines1.xml
      rwtestXmlRef musicxml/testLines2.xml
      rwtestXml musicxml/testLyricsVoice2a.xml
      rwtestXmlRef musicxml/testLyricsVoice2b.xml
      rwtestXmlRef musicxml/testMeasureLength.xml
      rwtestXml musicxml/testMetaData.xml
      rwtestXml musicxml/testMultiMeasureRest.xml
      rwtestXml musicxml/testNoteAttributes1.xml
      rwtestXml musicxml/testNoteAttributes2.xml
      rwtestXml musicxml/testNoteheads.xml
      rwtestXml musicxml/testNotesRests1.xml
      rwtestXml musicxml/testNotesRests2.xml
      rwtestXmlRef musicxml/testPartsSpecialCases.xml
      rwtestXml musicxml/testStaffTwoKeySigs.xml
      rwtestXml musicxml/testSystemBrackets1.xml
      rwtestXml musicxml/testSystemBrackets2.xml
      rwtestXml musicxml/testTempo1.xml
      rwtestXml musicxml/testTimesig1.xml
      rwtestXml musicxml/testTimesig3.xml
      rwtestXml musicxml/testTremolo.xml
      rwtestXml musicxml/testTuplets.xml
      rwtestXmlRef musicxml/testVoiceMapper1.xml
      rwtestXml musicxml/testVoicePiano1.xml
      rwtestXml musicxml/testVolta1.xml
      rwtestXml musicxml/testWedge1.xml
      rwtestXmlRef musicxml/testWedge2.xml
      rwtestXml musicxml/testWords1.xml
      }

usage() {
      echo "usage: $0 [bww | demos | msc | xml]"
      echo "or: $0 [bww | msc | xml] <file>"
      echo
      exit 1
      }

if [ $# -eq 0 ]; then
      rwtestAllBww
      rwtestAllDemos
      rwtestAllMsc
      rwtestAllXml
elif [ $# -eq 1 ]; then
      if [ "$1" == "bww" ]; then
            rwtestAllBww
      elif [ "$1" == "demos" ]; then
            rwtestAllDemos
      elif [ "$1" == "msc" ]; then
            rwtestAllMsc
      elif [ "$1" == "xml" ]; then
            rwtestAllXml
      else
            usage
      fi
elif [ $# -eq 2 ]; then
      if [ "$1" == "bww" ]; then
            rwtest $2
      elif [ "$1" == "msc" ]; then
            rwtest $2
      elif [ "$1" == "xml" ]; then
            rwtestXml $2
      else
            usage
      fi
elif [ $# -ge 3 ]; then
      usage
fi

echo
echo "$testcount test(s), $failures failure(s)"
